name: Process v1/v2 push or pr
on:
  push:
    branches:
      - feature/add-osmium
      - v2
      - v1
  pull_request:
    branches:
      - v2
      - v1
jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C ${{ matrix.build_type }}

  docker-push:
    if: github.ref == 'refs/heads/v1' || github.ref == 'refs/heads/v2' || github.ref == 'refs/heads/feature/add-osmium'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image from master and push it
        run: ./.github/workflows/scripts/build_and_push_dev.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}