name: Build stable from release
on:
  release:
    types:
      - published
jobs:
  prod-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${GITHUB_REF##*/} =~ ^v[1-9]\.[0-1]\.[0-9]$ ]]; then
              echo ::set-output name=match::true
          fi
      - name: Push latest image as prod
        if: steps.check-tag.outputs.match == 'true'
        run: ./.github/workflows/scripts/push_stable.sh
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_AUTH: ${{ secrets.DOCKER_AUTH }}